files:
- generatedChecksum: C2B88D9215301ECE3DC36E4B82F2791C
  logicalPath: config\pic32mx_xlp_sk
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: C2B88D9215301ECE3DC36E4B82F2791C
- generatedChecksum: B5E0444BF693E086E3AFE2916DE8EAFC
  logicalPath: config\pic32mx_xlp_sk
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: B5E0444BF693E086E3AFE2916DE8EAFC
- generatedChecksum: C1D449AC7B88EFA5FF8755CD4E3D7577
  logicalPath: config\pic32mx_xlp_sk
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: C1D449AC7B88EFA5FF8755CD4E3D7577
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 729CF148CCC881BCDA193C336D565A65
  logicalPath: config\pic32mx_xlp_sk\peripheral\clk
  name: plib_clk.c
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 729CF148CCC881BCDA193C336D565A65
- generatedChecksum: 1EDD7FCDB69F171C5E75C83C1479D888
  logicalPath: config\pic32mx_xlp_sk\peripheral\evic
  name: plib_evic.c
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 1EDD7FCDB69F171C5E75C83C1479D888
- generatedChecksum: 2583B7DBCDE32268F535A1843C7F1F99
  logicalPath: config\pic32mx_xlp_sk\peripheral\gpio
  name: plib_gpio.c
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2583B7DBCDE32268F535A1843C7F1F99
- generatedChecksum: F9B19CE376C55CECAD8422E6458C1958
  logicalPath: config\pic32mx_xlp_sk\peripheral\power
  name: plib_power.c
  physicalPath: peripheral\power
  security: NON_SECURE
  type: SOURCE
  userChecksum: F9B19CE376C55CECAD8422E6458C1958
- generatedChecksum: 3395BC7859A61CF74BB26386EF635C14
  logicalPath: config\pic32mx_xlp_sk\peripheral\rcon
  name: plib_rcon.c
  physicalPath: peripheral\rcon
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3395BC7859A61CF74BB26386EF635C14
- generatedChecksum: B01A54A60E37A0F3A459788E5BB8CD42
  logicalPath: config\pic32mx_xlp_sk\peripheral\tmr1
  name: plib_tmr1.c
  physicalPath: peripheral\tmr1
  security: NON_SECURE
  type: SOURCE
  userChecksum: B01A54A60E37A0F3A459788E5BB8CD42
- generatedChecksum: AEA3F49E924C04B1DC1275B0429B655B
  logicalPath: config\pic32mx_xlp_sk\peripheral\uart
  name: plib_uart1.c
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: AEA3F49E924C04B1DC1275B0429B655B
- generatedChecksum: A636C701B81D51E1D15E7ECB7F0FDE65
  logicalPath: config\pic32mx_xlp_sk\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: A636C701B81D51E1D15E7ECB7F0FDE65
- generatedChecksum: CD669CECB409CB45DBAD60196A5AA679
  logicalPath: config\pic32mx_xlp_sk
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: CD669CECB409CB45DBAD60196A5AA679
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config\pic32mx_xlp_sk
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config\pic32mx_xlp_sk
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config\pic32mx_xlp_sk\peripheral\clk
  name: plib_clk.h
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 3BE6DA6B5D6D8605EC41BCB0DF5C8C7A
  logicalPath: config\pic32mx_xlp_sk\peripheral\evic
  name: plib_evic.h
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 3BE6DA6B5D6D8605EC41BCB0DF5C8C7A
- generatedChecksum: 3A06A2AEB925D93E11EC81F664FE0913
  logicalPath: config\pic32mx_xlp_sk\peripheral\gpio
  name: plib_gpio.h
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 3A06A2AEB925D93E11EC81F664FE0913
- generatedChecksum: 4F9C653D6BD292D382A2FF8A96762854
  logicalPath: config\pic32mx_xlp_sk\peripheral\power
  name: plib_power.h
  physicalPath: peripheral\power
  security: NON_SECURE
  type: HEADER
  userChecksum: 4F9C653D6BD292D382A2FF8A96762854
- generatedChecksum: C5575FEA346C93F9F34B737226BDAEBC
  logicalPath: config\pic32mx_xlp_sk\peripheral\rcon
  name: plib_rcon.h
  physicalPath: peripheral\rcon
  security: NON_SECURE
  type: HEADER
  userChecksum: C5575FEA346C93F9F34B737226BDAEBC
- generatedChecksum: 32D7539D9231F3C159ABECE91A0281EA
  logicalPath: config\pic32mx_xlp_sk\peripheral\tmr1
  name: plib_tmr1.h
  physicalPath: peripheral\tmr1
  security: NON_SECURE
  type: HEADER
  userChecksum: 32D7539D9231F3C159ABECE91A0281EA
- generatedChecksum: 69E7C8CDAB1B32838331EE261170CEA4
  logicalPath: config\pic32mx_xlp_sk\peripheral\tmr1
  name: plib_tmr1_common.h
  physicalPath: peripheral\tmr1
  security: NON_SECURE
  type: HEADER
  userChecksum: 69E7C8CDAB1B32838331EE261170CEA4
- generatedChecksum: 6688F1ADA16F2A2759A3C2D93250963D
  logicalPath: config\pic32mx_xlp_sk\peripheral\uart
  name: plib_uart1.h
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 6688F1ADA16F2A2759A3C2D93250963D
- generatedChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
  logicalPath: config\pic32mx_xlp_sk\peripheral\uart
  name: plib_uart_common.h
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 67EEAF539A53B6B8FD7B600ACCB3F3CA
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config\pic32mx_xlp_sk
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: B5F47976A7C4FCA48A55D10AF6CEF6F6
  logicalPath: config\pic32mx_xlp_sk
  name: p32MX274F256D.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: B5F47976A7C4FCA48A55D10AF6CEF6F6
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mx_xlp_sk;../src/packs/PIC32MX274F256D_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mx_xlp_sk;../src/packs/PIC32MX274F256D_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
