format_version: v1.0
type: UniqueComponent
attributes: {id: tmr2}
children:
- type: Symbols
  children:
  - type: Hex
    attributes: {id: TCON_REG_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr2, value: '0'}
  - type: Integer
    attributes: {id: TIMER_CLOCK_FREQ}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr2, value: '36000000'}
  - type: Long
    attributes: {id: TIMER_PERIOD}
    children:
    - type: Attributes
      children:
      - type: Long
        attributes: {id: max}
        children:
        - {type: Value, value: '65535'}
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr2, value: '35999'}
  - type: Float
    attributes: {id: TIMER_TIME_PERIOD_MS}
    children:
    - type: Attributes
      children:
      - type: Float
        attributes: {id: max}
        children:
        - {type: Value, value: '1.8204722'}
    - type: Values
      children:
      - type: User
        attributes: {value: '1.0'}
  - type: String
    attributes: {id: TMR_IEC_REG}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr2, value: IEC0}
  - type: String
    attributes: {id: TMR_IFS_REG}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr2, value: IFS0}
  - type: Boolean
    attributes: {id: TMR_INTERRUPT_MODE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr2, value: 'true'}
      - type: User
        attributes: {value: 'false'}
  - type: Integer
    attributes: {id: TMR_PRESCALER_VALUE}
    children:
    - type: Values
      children:
      - type: Dynamic
        attributes: {id: tmr2, value: '1'}
- type: ElementPosition
  attributes: {x: '38', y: '131', id: tmr2}
