files:
- generatedChecksum: 99DB74296DF9943C474F4F03A700C790
  logicalPath: config/pic32mx470_curiosity
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 99DB74296DF9943C474F4F03A700C790
- generatedChecksum: 9E0AEE0DD7638AA5A12C30A7F959CB00
  logicalPath: config/pic32mx470_curiosity
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9E0AEE0DD7638AA5A12C30A7F959CB00
- generatedChecksum: 2593A48A9BDCCF2533CF29C6099DC002
  logicalPath: config/pic32mx470_curiosity
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 2593A48A9BDCCF2533CF29C6099DC002
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: E78B3EC1DDDC45026163CEB430466288
  logicalPath: config/pic32mx470_curiosity/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: E78B3EC1DDDC45026163CEB430466288
- generatedChecksum: CDE489012C46160ED6A67092B2FFCE99
  logicalPath: config/pic32mx470_curiosity/peripheral/coretimer
  name: plib_coretimer.c
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: SOURCE
  userChecksum: CDE489012C46160ED6A67092B2FFCE99
- generatedChecksum: F2A637157B7BEAABE1F32440D81B2AC1
  logicalPath: config/pic32mx470_curiosity/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: F2A637157B7BEAABE1F32440D81B2AC1
- generatedChecksum: 802B6B0F050F31A508B8C42D5DF6FD6D
  logicalPath: config/pic32mx470_curiosity/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 802B6B0F050F31A508B8C42D5DF6FD6D
- generatedChecksum: 3395BC7859A61CF74BB26386EF635C14
  logicalPath: config/pic32mx470_curiosity/peripheral/rcon
  name: plib_rcon.c
  physicalPath: peripheral/rcon
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3395BC7859A61CF74BB26386EF635C14
- generatedChecksum: 7839BF01CED9432B7210B376E179A787
  logicalPath: config/pic32mx470_curiosity/peripheral/uart
  name: plib_uart1.c
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7839BF01CED9432B7210B376E179A787
- generatedChecksum: F692CD3BEAAFCAA63048D2A59DCFFBC9
  logicalPath: config/pic32mx470_curiosity/peripheral/wdt
  name: plib_wdt.c
  physicalPath: peripheral/wdt
  security: NON_SECURE
  type: SOURCE
  userChecksum: F692CD3BEAAFCAA63048D2A59DCFFBC9
- generatedChecksum: A636C701B81D51E1D15E7ECB7F0FDE65
  logicalPath: config/pic32mx470_curiosity/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: A636C701B81D51E1D15E7ECB7F0FDE65
- generatedChecksum: DE65D7D05ABB6CCE5957585CF68A4061
  logicalPath: config/pic32mx470_curiosity
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: DE65D7D05ABB6CCE5957585CF68A4061
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mx470_curiosity
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mx470_curiosity
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mx470_curiosity/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: FEC404CF9C8FD62A846AD55416BAC416
  logicalPath: config/pic32mx470_curiosity/peripheral/coretimer
  name: plib_coretimer.h
  physicalPath: peripheral/coretimer
  security: NON_SECURE
  type: HEADER
  userChecksum: FEC404CF9C8FD62A846AD55416BAC416
- generatedChecksum: A2CC849C687144A046545E8CF6188343
  logicalPath: config/pic32mx470_curiosity/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: A2CC849C687144A046545E8CF6188343
- generatedChecksum: 5FCC2C807792B8E3C99AB36ACA0FC80E
  logicalPath: config/pic32mx470_curiosity/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 5FCC2C807792B8E3C99AB36ACA0FC80E
- generatedChecksum: 439770492A0C6288C6FA5FB1029B473C
  logicalPath: config/pic32mx470_curiosity/peripheral/rcon
  name: plib_rcon.h
  physicalPath: peripheral/rcon
  security: NON_SECURE
  type: HEADER
  userChecksum: 439770492A0C6288C6FA5FB1029B473C
- generatedChecksum: 991F2B1F3EA07254B6A9C096A3CDDFD6
  logicalPath: config/pic32mx470_curiosity/peripheral/uart
  name: plib_uart1.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 991F2B1F3EA07254B6A9C096A3CDDFD6
- generatedChecksum: 91611515A95D92B82B7F4064C16D122B
  logicalPath: config/pic32mx470_curiosity/peripheral/uart
  name: plib_uart_common.h
  physicalPath: peripheral/uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 91611515A95D92B82B7F4064C16D122B
- generatedChecksum: 52646F9F1734C5AA98A212549F6FE3E3
  logicalPath: config/pic32mx470_curiosity/peripheral/wdt
  name: plib_wdt.h
  physicalPath: peripheral/wdt
  security: NON_SECURE
  type: HEADER
  userChecksum: 52646F9F1734C5AA98A212549F6FE3E3
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config/pic32mx470_curiosity
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: 52AA20E8BAA488B3B6581379249C0FCE
  logicalPath: config/pic32mx470_curiosity
  name: p32MX470F512H.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 52AA20E8BAA488B3B6581379249C0FCE
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mx470_curiosity;
- append: false
  category: C32
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mx470_curiosity;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
