files:
- generatedChecksum: 99DB74296DF9943C474F4F03A700C790
  logicalPath: config/pic32mx470_curiosity
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 99DB74296DF9943C474F4F03A700C790
- generatedChecksum: 7B0FB0F7C6DFFAACD0037147490E2319
  logicalPath: config/pic32mx470_curiosity
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7B0FB0F7C6DFFAACD0037147490E2319
- generatedChecksum: 4B6A778CF4449A8EC938F5D4D0917E56
  logicalPath: config/pic32mx470_curiosity
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4B6A778CF4449A8EC938F5D4D0917E56
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ../..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 1FDF0D577E0257B1D8FA547AED78E48E
  logicalPath: config/pic32mx470_curiosity/peripheral/clk
  name: plib_clk.c
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 1FDF0D577E0257B1D8FA547AED78E48E
- generatedChecksum: 36F718A0C383C0856EB1DE4DEA41B4D5
  logicalPath: config/pic32mx470_curiosity/peripheral/evic
  name: plib_evic.c
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 36F718A0C383C0856EB1DE4DEA41B4D5
- generatedChecksum: CFBB4DE25A8CF8FD30BA25BDBC430FE3
  logicalPath: config/pic32mx470_curiosity/peripheral/gpio
  name: plib_gpio.c
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: CFBB4DE25A8CF8FD30BA25BDBC430FE3
- generatedChecksum: FCE1CC017013237DECE67A9273B1C714
  logicalPath: config/pic32mx470_curiosity/peripheral/ocmp
  name: plib_ocmp1.c
  physicalPath: peripheral/ocmp
  security: NON_SECURE
  type: SOURCE
  userChecksum: FCE1CC017013237DECE67A9273B1C714
- generatedChecksum: 6CBC84EA48AD8B13D49C502FA2115512
  logicalPath: config/pic32mx470_curiosity/peripheral/ocmp
  name: plib_ocmp2.c
  physicalPath: peripheral/ocmp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6CBC84EA48AD8B13D49C502FA2115512
- generatedChecksum: 456DFE4F24D0805414203884AC4035FE
  logicalPath: config/pic32mx470_curiosity/peripheral/ocmp
  name: plib_ocmp3.c
  physicalPath: peripheral/ocmp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 456DFE4F24D0805414203884AC4035FE
- generatedChecksum: 9A10BF8AC6610A41C75814EEB8BF0924
  logicalPath: config/pic32mx470_curiosity/peripheral/tmr
  name: plib_tmr2.c
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: SOURCE
  userChecksum: 9A10BF8AC6610A41C75814EEB8BF0924
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config/pic32mx470_curiosity/stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: 8C3CB2505E57DA17AB584893E8A19215
  logicalPath: config/pic32mx470_curiosity
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 8C3CB2505E57DA17AB584893E8A19215
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config/pic32mx470_curiosity
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config/pic32mx470_curiosity
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config/pic32mx470_curiosity/peripheral/clk
  name: plib_clk.h
  physicalPath: peripheral/clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: A2CC849C687144A046545E8CF6188343
  logicalPath: config/pic32mx470_curiosity/peripheral/evic
  name: plib_evic.h
  physicalPath: peripheral/evic
  security: NON_SECURE
  type: HEADER
  userChecksum: A2CC849C687144A046545E8CF6188343
- generatedChecksum: 3034BE358F7BD4B7B31FE392CCBDA3D6
  logicalPath: config/pic32mx470_curiosity/peripheral/gpio
  name: plib_gpio.h
  physicalPath: peripheral/gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 3034BE358F7BD4B7B31FE392CCBDA3D6
- generatedChecksum: 76AA999BA6C34DEAF6C37E3E0695C45E
  logicalPath: config/pic32mx470_curiosity/peripheral/ocmp
  name: plib_ocmp1.h
  physicalPath: peripheral/ocmp
  security: NON_SECURE
  type: HEADER
  userChecksum: 76AA999BA6C34DEAF6C37E3E0695C45E
- generatedChecksum: 13EE9B5E82F59CC57E429D234B2B6FB3
  logicalPath: config/pic32mx470_curiosity/peripheral/ocmp
  name: plib_ocmp2.h
  physicalPath: peripheral/ocmp
  security: NON_SECURE
  type: HEADER
  userChecksum: 13EE9B5E82F59CC57E429D234B2B6FB3
- generatedChecksum: 92F5C35DF062E420C1899CB3343BE8FA
  logicalPath: config/pic32mx470_curiosity/peripheral/ocmp
  name: plib_ocmp3.h
  physicalPath: peripheral/ocmp
  security: NON_SECURE
  type: HEADER
  userChecksum: 92F5C35DF062E420C1899CB3343BE8FA
- generatedChecksum: C7376B9C0FE98B35880E7395A16846B2
  logicalPath: config/pic32mx470_curiosity/peripheral/ocmp
  name: plib_ocmp_common.h
  physicalPath: peripheral/ocmp
  security: NON_SECURE
  type: HEADER
  userChecksum: C7376B9C0FE98B35880E7395A16846B2
- generatedChecksum: 9DF2058BBA7397756E0CED63F294C4C3
  logicalPath: config/pic32mx470_curiosity/peripheral/tmr
  name: plib_tmr2.h
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: 9DF2058BBA7397756E0CED63F294C4C3
- generatedChecksum: D948F2CE092CAB556EF299D3CCD83A55
  logicalPath: config/pic32mx470_curiosity/peripheral/tmr
  name: plib_tmr_common.h
  physicalPath: peripheral/tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: D948F2CE092CAB556EF299D3CCD83A55
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config/pic32mx470_curiosity
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: 52AA20E8BAA488B3B6581379249C0FCE
  logicalPath: config/pic32mx470_curiosity
  name: p32MX470F512H.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 52AA20E8BAA488B3B6581379249C0FCE
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mx470_curiosity;
- append: false
  category: C32
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mx470_curiosity;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
