files:
- generatedChecksum: C2B88D9215301ECE3DC36E4B82F2791C
  logicalPath: config\pic32mx470_curiosity
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: C2B88D9215301ECE3DC36E4B82F2791C
- generatedChecksum: 6841051E7E8D8CE28D4460FCEA2A6E60
  logicalPath: config\pic32mx470_curiosity
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6841051E7E8D8CE28D4460FCEA2A6E60
- generatedChecksum: 4B6A778CF4449A8EC938F5D4D0917E56
  logicalPath: config\pic32mx470_curiosity
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4B6A778CF4449A8EC938F5D4D0917E56
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 912AF4A333F4F4FE8EBB74CF1E90508C
  logicalPath: config\pic32mx470_curiosity\peripheral\clk
  name: plib_clk.c
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 912AF4A333F4F4FE8EBB74CF1E90508C
- generatedChecksum: 36F718A0C383C0856EB1DE4DEA41B4D5
  logicalPath: config\pic32mx470_curiosity\peripheral\evic
  name: plib_evic.c
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 36F718A0C383C0856EB1DE4DEA41B4D5
- generatedChecksum: 0B0A5B5984E363BE97BF338915D5644A
  logicalPath: config\pic32mx470_curiosity\peripheral\gpio
  name: plib_gpio.c
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0B0A5B5984E363BE97BF338915D5644A
- generatedChecksum: 0E85B0AB5FCB309535FF33FDEA0982C4
  logicalPath: config\pic32mx470_curiosity\peripheral\icap
  name: plib_icap1.c
  physicalPath: peripheral\icap
  security: NON_SECURE
  type: SOURCE
  userChecksum: 0E85B0AB5FCB309535FF33FDEA0982C4
- generatedChecksum: 1A6F78907CA4300156425C1382FAFAA7
  logicalPath: config\pic32mx470_curiosity\peripheral\ocmp
  name: plib_ocmp3.c
  physicalPath: peripheral\ocmp
  security: NON_SECURE
  type: SOURCE
  userChecksum: 1A6F78907CA4300156425C1382FAFAA7
- generatedChecksum: 01C90FC502B55194EB6FD36F151F3C63
  logicalPath: config\pic32mx470_curiosity\peripheral\tmr
  name: plib_tmr2.c
  physicalPath: peripheral\tmr
  security: NON_SECURE
  type: SOURCE
  userChecksum: 01C90FC502B55194EB6FD36F151F3C63
- generatedChecksum: 7839BF01CED9432B7210B376E179A787
  logicalPath: config\pic32mx470_curiosity\peripheral\uart
  name: plib_uart1.c
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7839BF01CED9432B7210B376E179A787
- generatedChecksum: A636C701B81D51E1D15E7ECB7F0FDE65
  logicalPath: config\pic32mx470_curiosity\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: A636C701B81D51E1D15E7ECB7F0FDE65
- generatedChecksum: 89E2EB902C68ED86C4A452550CFC06D8
  logicalPath: config\pic32mx470_curiosity
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 89E2EB902C68ED86C4A452550CFC06D8
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config\pic32mx470_curiosity
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config\pic32mx470_curiosity
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config\pic32mx470_curiosity\peripheral\clk
  name: plib_clk.h
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: A2CC849C687144A046545E8CF6188343
  logicalPath: config\pic32mx470_curiosity\peripheral\evic
  name: plib_evic.h
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: HEADER
  userChecksum: A2CC849C687144A046545E8CF6188343
- generatedChecksum: 3034BE358F7BD4B7B31FE392CCBDA3D6
  logicalPath: config\pic32mx470_curiosity\peripheral\gpio
  name: plib_gpio.h
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 3034BE358F7BD4B7B31FE392CCBDA3D6
- generatedChecksum: C735FE07D839BEF0340E5DD22C2DCC74
  logicalPath: config\pic32mx470_curiosity\peripheral\icap
  name: plib_icap1.h
  physicalPath: peripheral\icap
  security: NON_SECURE
  type: HEADER
  userChecksum: C735FE07D839BEF0340E5DD22C2DCC74
- generatedChecksum: B75BC5AEF7A117FB761A3A8548E16E3D
  logicalPath: config\pic32mx470_curiosity\peripheral\icap
  name: plib_icap_common.h
  physicalPath: peripheral\icap
  security: NON_SECURE
  type: HEADER
  userChecksum: B75BC5AEF7A117FB761A3A8548E16E3D
- generatedChecksum: E30FFC13DBD9F668569DE45E56387DCD
  logicalPath: config\pic32mx470_curiosity\peripheral\ocmp
  name: plib_ocmp3.h
  physicalPath: peripheral\ocmp
  security: NON_SECURE
  type: HEADER
  userChecksum: E30FFC13DBD9F668569DE45E56387DCD
- generatedChecksum: C7376B9C0FE98B35880E7395A16846B2
  logicalPath: config\pic32mx470_curiosity\peripheral\ocmp
  name: plib_ocmp_common.h
  physicalPath: peripheral\ocmp
  security: NON_SECURE
  type: HEADER
  userChecksum: C7376B9C0FE98B35880E7395A16846B2
- generatedChecksum: 9DF2058BBA7397756E0CED63F294C4C3
  logicalPath: config\pic32mx470_curiosity\peripheral\tmr
  name: plib_tmr2.h
  physicalPath: peripheral\tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: 9DF2058BBA7397756E0CED63F294C4C3
- generatedChecksum: D948F2CE092CAB556EF299D3CCD83A55
  logicalPath: config\pic32mx470_curiosity\peripheral\tmr
  name: plib_tmr_common.h
  physicalPath: peripheral\tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: D948F2CE092CAB556EF299D3CCD83A55
- generatedChecksum: 991F2B1F3EA07254B6A9C096A3CDDFD6
  logicalPath: config\pic32mx470_curiosity\peripheral\uart
  name: plib_uart1.h
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 991F2B1F3EA07254B6A9C096A3CDDFD6
- generatedChecksum: 91611515A95D92B82B7F4064C16D122B
  logicalPath: config\pic32mx470_curiosity\peripheral\uart
  name: plib_uart_common.h
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 91611515A95D92B82B7F4064C16D122B
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config\pic32mx470_curiosity
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: A26CA65B6345DAB213FD6F3026F7F238
  logicalPath: config\pic32mx470_curiosity
  name: p32MX470F512H.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: A26CA65B6345DAB213FD6F3026F7F238
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mx470_curiosity;../src/packs/PIC32MX470F512H_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mx470_curiosity;../src/packs/PIC32MX470F512H_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
