files:
- generatedChecksum: C2B88D9215301ECE3DC36E4B82F2791C
  logicalPath: config\pic32mx_sk
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: C2B88D9215301ECE3DC36E4B82F2791C
- generatedChecksum: AE81CD87A69F83B09407E7AE4BF7FFFA
  logicalPath: config\pic32mx_sk
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: AE81CD87A69F83B09407E7AE4BF7FFFA
- generatedChecksum: 20F22B70C4B0B528FEFE85C97C72531F
  logicalPath: config\pic32mx_sk
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: 20F22B70C4B0B528FEFE85C97C72531F
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 6902DD0021DA94F42DE165233780733C
  logicalPath: config\pic32mx_sk\peripheral\clk
  name: plib_clk.c
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 6902DD0021DA94F42DE165233780733C
- generatedChecksum: 1C64A0CC3068C1F1EB55F6817B1579A6
  logicalPath: config\pic32mx_sk\peripheral\coretimer
  name: plib_coretimer.c
  physicalPath: peripheral\coretimer
  security: NON_SECURE
  type: SOURCE
  userChecksum: 1C64A0CC3068C1F1EB55F6817B1579A6
- generatedChecksum: 648D3B13F6BFF0A300471D955302CC32
  logicalPath: config\pic32mx_sk\peripheral\evic
  name: plib_evic.c
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 648D3B13F6BFF0A300471D955302CC32
- generatedChecksum: D73ECD9B88A7D5BB5CD7DE7AEE6A08A9
  logicalPath: config\pic32mx_sk\peripheral\gpio
  name: plib_gpio.c
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: D73ECD9B88A7D5BB5CD7DE7AEE6A08A9
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config\pic32mx_sk\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: 7861F41195BAE64E8E4D88C496E02872
  logicalPath: config\pic32mx_sk
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 7861F41195BAE64E8E4D88C496E02872
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config\pic32mx_sk
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config\pic32mx_sk
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config\pic32mx_sk\peripheral\clk
  name: plib_clk.h
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 6E3A0600FD4201EB1D41667682B4D4B1
  logicalPath: config\pic32mx_sk\peripheral\coretimer
  name: plib_coretimer.h
  physicalPath: peripheral\coretimer
  security: NON_SECURE
  type: HEADER
  userChecksum: 6E3A0600FD4201EB1D41667682B4D4B1
- generatedChecksum: 08CAE57066302D12E2A32EE07E935AFE
  logicalPath: config\pic32mx_sk\peripheral\evic
  name: plib_evic.h
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 08CAE57066302D12E2A32EE07E935AFE
- generatedChecksum: C1EB062D51D4DC89BC81848B4E9A46DC
  logicalPath: config\pic32mx_sk\peripheral\gpio
  name: plib_gpio.h
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: C1EB062D51D4DC89BC81848B4E9A46DC
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config\pic32mx_sk
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: D3313458AC706756FC68F2CE1408ECFF
  logicalPath: config\pic32mx_sk
  name: p32MX360F512L.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: D3313458AC706756FC68F2CE1408ECFF
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mx_sk;../src/packs/PIC32MX360F512L_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mx_sk;../src/packs/PIC32MX360F512L_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
