files:
- generatedChecksum: C2B88D9215301ECE3DC36E4B82F2791C
  logicalPath: config\pic32mx470_curiosity
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: C2B88D9215301ECE3DC36E4B82F2791C
- generatedChecksum: C0FB4AF1B2EAF62B768087B34862AC61
  logicalPath: config\pic32mx470_curiosity
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: C0FB4AF1B2EAF62B768087B34862AC61
- generatedChecksum: DF4FDCA48FF3E50233754D4E363F48C9
  logicalPath: config\pic32mx470_curiosity
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: DF4FDCA48FF3E50233754D4E363F48C9
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 4EE75787E86B5235133A7EFEE103FD31
  logicalPath: config\pic32mx470_curiosity\peripheral\clk
  name: plib_clk.c
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4EE75787E86B5235133A7EFEE103FD31
- generatedChecksum: 5F75FA6B24BA18031B68978847CB4FA2
  logicalPath: config\pic32mx470_curiosity\peripheral\evic
  name: plib_evic.c
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: 5F75FA6B24BA18031B68978847CB4FA2
- generatedChecksum: B36EF3A5E8E8660F74265D3548AAF4C3
  logicalPath: config\pic32mx470_curiosity\peripheral\gpio
  name: plib_gpio.c
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: B36EF3A5E8E8660F74265D3548AAF4C3
- generatedChecksum: 4CD2086BA0B67A4793BAE51C84901BAA
  logicalPath: config\pic32mx470_curiosity\peripheral\rtcc
  name: plib_rtcc.c
  physicalPath: peripheral\rtcc
  security: NON_SECURE
  type: SOURCE
  userChecksum: 4CD2086BA0B67A4793BAE51C84901BAA
- generatedChecksum: 7839BF01CED9432B7210B376E179A787
  logicalPath: config\pic32mx470_curiosity\peripheral\uart
  name: plib_uart1.c
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7839BF01CED9432B7210B376E179A787
- generatedChecksum: A636C701B81D51E1D15E7ECB7F0FDE65
  logicalPath: config\pic32mx470_curiosity\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: A636C701B81D51E1D15E7ECB7F0FDE65
- generatedChecksum: 9AA31060C6764EBA7EFC6262B6E7D082
  logicalPath: config\pic32mx470_curiosity
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 9AA31060C6764EBA7EFC6262B6E7D082
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config\pic32mx470_curiosity
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config\pic32mx470_curiosity
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config\pic32mx470_curiosity\peripheral\clk
  name: plib_clk.h
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: A2CC849C687144A046545E8CF6188343
  logicalPath: config\pic32mx470_curiosity\peripheral\evic
  name: plib_evic.h
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: HEADER
  userChecksum: A2CC849C687144A046545E8CF6188343
- generatedChecksum: 3034BE358F7BD4B7B31FE392CCBDA3D6
  logicalPath: config\pic32mx470_curiosity\peripheral\gpio
  name: plib_gpio.h
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 3034BE358F7BD4B7B31FE392CCBDA3D6
- generatedChecksum: C5CCB53DBC284D1BCEAB7756ED870B04
  logicalPath: config\pic32mx470_curiosity\peripheral\rtcc
  name: plib_rtcc.h
  physicalPath: peripheral\rtcc
  security: NON_SECURE
  type: HEADER
  userChecksum: C5CCB53DBC284D1BCEAB7756ED870B04
- generatedChecksum: 991F2B1F3EA07254B6A9C096A3CDDFD6
  logicalPath: config\pic32mx470_curiosity\peripheral\uart
  name: plib_uart1.h
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 991F2B1F3EA07254B6A9C096A3CDDFD6
- generatedChecksum: 91611515A95D92B82B7F4064C16D122B
  logicalPath: config\pic32mx470_curiosity\peripheral\uart
  name: plib_uart_common.h
  physicalPath: peripheral\uart
  security: NON_SECURE
  type: HEADER
  userChecksum: 91611515A95D92B82B7F4064C16D122B
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config\pic32mx470_curiosity
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: A26CA65B6345DAB213FD6F3026F7F238
  logicalPath: config\pic32mx470_curiosity
  name: p32MX470F512H.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: A26CA65B6345DAB213FD6F3026F7F238
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mx470_curiosity;../src/packs/PIC32MX470F512H_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mx470_curiosity;../src/packs/PIC32MX470F512H_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
