files:
- generatedChecksum: C2B88D9215301ECE3DC36E4B82F2791C
  logicalPath: config\pic32mx_usb_sk3
  name: exceptions.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: C2B88D9215301ECE3DC36E4B82F2791C
- generatedChecksum: A1617176B8802EFF5B3BCBABDFFEC430
  logicalPath: config\pic32mx_usb_sk3
  name: initialization.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: A1617176B8802EFF5B3BCBABDFFEC430
- generatedChecksum: A3B1B3B09627EB7EED7D65D44D5F6D59
  logicalPath: config\pic32mx_usb_sk3
  name: interrupts.c
  physicalPath: ''
  security: NON_SECURE
  type: SOURCE
  userChecksum: A3B1B3B09627EB7EED7D65D44D5F6D59
- generatedChecksum: null
  logicalPath: ''
  name: main.c
  physicalPath: ..\..
  security: NON_SECURE
  type: SOURCE
  userChecksum: null
- generatedChecksum: 3836332FDC338A07C08251C107BDFFC1
  logicalPath: config\pic32mx_usb_sk3\peripheral\clk
  name: plib_clk.c
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: SOURCE
  userChecksum: 3836332FDC338A07C08251C107BDFFC1
- generatedChecksum: FE1025BB5BBC054E383E3C08AAE6C003
  logicalPath: config\pic32mx_usb_sk3\peripheral\evic
  name: plib_evic.c
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: SOURCE
  userChecksum: FE1025BB5BBC054E383E3C08AAE6C003
- generatedChecksum: 70BF9699D0DCED7DEED828A59C79B95C
  logicalPath: config\pic32mx_usb_sk3\peripheral\gpio
  name: plib_gpio.c
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 70BF9699D0DCED7DEED828A59C79B95C
- generatedChecksum: 7EF47F49A6E1151CC1A8A92527DDD3E2
  logicalPath: config\pic32mx_usb_sk3\peripheral\tmr
  name: plib_tmr2.c
  physicalPath: peripheral\tmr
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7EF47F49A6E1151CC1A8A92527DDD3E2
- generatedChecksum: 7806B30ECAE0D18D08CD583D8775530D
  logicalPath: config\pic32mx_usb_sk3\stdio
  name: xc32_monitor.c
  physicalPath: stdio
  security: NON_SECURE
  type: SOURCE
  userChecksum: 7806B30ECAE0D18D08CD583D8775530D
- generatedChecksum: 8D3C849EBB4C04E7D6AB7F8CA5C5A856
  logicalPath: config\pic32mx_usb_sk3
  name: definitions.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 8D3C849EBB4C04E7D6AB7F8CA5C5A856
- generatedChecksum: E189C26B2269F8DE46033CCD0621958D
  logicalPath: config\pic32mx_usb_sk3
  name: device.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: E189C26B2269F8DE46033CCD0621958D
- generatedChecksum: 4CF4A86296482D5331331BA301C20BB2
  logicalPath: config\pic32mx_usb_sk3
  name: interrupts.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 4CF4A86296482D5331331BA301C20BB2
- generatedChecksum: 7066CC390335CF75126E2A50C46E3BDD
  logicalPath: config\pic32mx_usb_sk3\peripheral\clk
  name: plib_clk.h
  physicalPath: peripheral\clk
  security: NON_SECURE
  type: HEADER
  userChecksum: 7066CC390335CF75126E2A50C46E3BDD
- generatedChecksum: 75248CE0895A5DB671AC2F4E9D0392C9
  logicalPath: config\pic32mx_usb_sk3\peripheral\evic
  name: plib_evic.h
  physicalPath: peripheral\evic
  security: NON_SECURE
  type: HEADER
  userChecksum: 75248CE0895A5DB671AC2F4E9D0392C9
- generatedChecksum: 6D1477A995C14AAFB0A44422D9840003
  logicalPath: config\pic32mx_usb_sk3\peripheral\gpio
  name: plib_gpio.h
  physicalPath: peripheral\gpio
  security: NON_SECURE
  type: HEADER
  userChecksum: 6D1477A995C14AAFB0A44422D9840003
- generatedChecksum: 951CB6B720EFCD3044875413BC7D7773
  logicalPath: config\pic32mx_usb_sk3\peripheral\tmr
  name: plib_tmr2.h
  physicalPath: peripheral\tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: 951CB6B720EFCD3044875413BC7D7773
- generatedChecksum: D948F2CE092CAB556EF299D3CCD83A55
  logicalPath: config\pic32mx_usb_sk3\peripheral\tmr
  name: plib_tmr_common.h
  physicalPath: peripheral\tmr
  security: NON_SECURE
  type: HEADER
  userChecksum: D948F2CE092CAB556EF299D3CCD83A55
- generatedChecksum: 2C8543317B3F067432097AB9BD3E8672
  logicalPath: config\pic32mx_usb_sk3
  name: toolchain_specifics.h
  physicalPath: ''
  security: NON_SECURE
  type: HEADER
  userChecksum: 2C8543317B3F067432097AB9BD3E8672
- generatedChecksum: 5C7BDB1F664D5637F66B6DA86B75CA2E
  logicalPath: config\pic32mx_usb_sk3
  name: p32MX470F512L.ld
  physicalPath: ''
  security: NON_SECURE
  type: LINKER
  userChecksum: 5C7BDB1F664D5637F66B6DA86B75CA2E
format_version: v1.0
libraries: []
settings:
- append: true
  category: C32
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mx_usb_sk3;../src/packs/PIC32MX470F512L_DFP;
- append: false
  category: C32
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
- append: false
  category: C32-LD
  delimiter: ''
  key: heap-size
  security: NON_SECURE
  value: '512'
- append: false
  category: C32-LD
  delimiter: ''
  key: no-device-startup-code
  security: NON_SECURE
  value: 'true'
- append: true
  category: C32-LD
  delimiter: ;=
  key: preprocessor-macros
  security: NON_SECURE
  value: ''
- append: true
  category: C32CPP
  delimiter: ;
  key: extra-include-directories
  security: NON_SECURE
  value: ../src;../src/config/pic32mx_usb_sk3;../src/packs/PIC32MX470F512L_DFP;
- append: false
  category: C32CPP
  delimiter: ''
  key: generate-16-bit-code
  security: NON_SECURE
  value: 'false'
sourcePaths: []
